version: "3.9"
services:
  db:
    container_name: postgres
    image: postgres
    shm_size: 128mb
    volumes:
      - postgresdb:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - hackathon
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123"
      PGDATA: /data/postgres
      POSTGRES_DB: hack
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  iceberg:
    container_name: iceberg-service
    image: ghcr.io/wedonttestanymore/iceberg-service:latest
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
    networks:
      - hackathon

  delta:
    container_name: delta-service
    image: ghcr.io/wedonttestanymore/delta-service:latest
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    networks:
      - hackathon

  hudi:
    container_name: hudi-service
    image: ghcr.io/wedonttestanymore/hudi-service:latest
    ports:
      - "8000:8000"
    networks:
      - hackathon

  parquet:
    container_name: parquet-service
    image: ghcr.io/wedonttestanymore/parquet-service:latest
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
    networks:
      - hackathon

  backend:
    image: ghcr.io/wedonttestanymore/api-service
    container_name: api_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - DB_URI=postgresql://root:123@db:5432/hack
      - LOGGING=1
      - BACKEND_PORT=3000
      - COOKIE_TIMEOUT_MIN=60
      - MAX_SCAN_DEPTH=2
      - ICEBERG_SERVICE_URL=http://iceberg-service:3001
      - DELTA_SERVICE_URL=http://delta-service:3002
      - HUDI_SERVICE_URL=http://hudi-service:8000
      - PARQUET_SERVICE_URL=http://parquet-service:3004
    restart: unless-stopped
    networks:
      - hackathon

  frontend:
    image: ghcr.io/wedonttestanymore/webapp
    container_name: webapp
    depends_on:
      - backend
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - hackathon
volumes:
  postgresdb:
#  minio_data:
#  backend_logs:

networks:
  hackathon:
    driver: bridge
