version: "3.9"
services:
  db:
    container_name: postgres
    image: postgres
    shm_size: 128mb
    volumes:
      - postgresdb:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - hackathon
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123"
      PGDATA: /data/postgres
      POSTGRES_DB: hack
    restart: unless-stopped

  iceberg:
    container_name: iceberg-service
    image: ghcr.io/wedonttestanymore/iceberg-service:latest
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
    networks:
      - hackathon

  delta:
    container_name: delta-service
    image: ghcr.io/wedonttestanymore/delta-service:latest
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    networks:
      - hackathon

  hudi:
    container_name: hudi-service
    image: ghcr.io/wedonttestanymore/hudi-service:latest
    ports:
      - "8000:8000"
    networks:
      - hackathon

  parquet:
    container_name: parquet-service
    image: ghcr.io/wedonttestanymore/parquet-service:latest
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
    networks:
      - hackathon

  backend:
    image: ghcr.io/wedonttestanymore/api-service
    container_name: api_backend
    depends_on:
      - db
      - minio
    ports:
      - "3000:3000"
    networks:
      - hackathon
    environment:
      - DB_URI=postgresql://root:123@db:5432/hack
      - LOGGING=1
      - BACKEND_PORT=3000
      - COOKIE_TIMEOUT_MIN=60
      - MAX_SCAN_DEPTH=2
      - ICEBERG_SERVICE_URL=http://iceberg-service:3001
      - DELTA_SERVICE_URL=http://delta-service:3002
      - HUDI_SERVICE_URL=http://hudi-service:8000
      - PARQUET_SERVICE_URL=http://parquet-service:3004
      - BUCKET_URI=http://minio:9000
    restart: unless-stopped

  frontend:
    image: ghcr.io/wedonttestanymore/webapp
    container_name: webapp
    depends_on:
      - backend
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - hackathon

  minio:
    hostname: minio
    image: 'minio/minio:RELEASE.2022-05-26T05-48-41Z'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - trino-docker_minio_data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"

volumes:
  postgresdb:
  trino-docker_minio_data:
    external: true

networks:
  hackathon:
    driver: bridge
