version: "3.9"
# Sample postgres db for testing
services:
  db:
    container_name: postgres
    image: postgres
    shm_size: 128mb
    volumes:
      - postgresdb:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - hackathon
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123"
      PGDATA: /data/postgres
      POSTGRES_DB: hack
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Adminer for db
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  # MinIO bucket for local s3 storage
  # minio:
  #   image: minio/minio
  #   container_name: minio
  #   ports:
  #     - "9000:9000" # API port
  #     - "9001:9001" # Console port
  #   volumes:
  #     - minio_data:/data
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   command: server --console-address ":9001" /data
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #   restart: unless-stopped

  delta:
    container_name: delta
    image: delta-service:latest
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    networks:
      - hackathon
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_backend
    depends_on:
      db:
        condition: service_healthy
    #minio:
    #  condition: service_healthy # Not really
    ports:
      - "3000:3000"
    environment:
      - DB_URI=postgresql://root:123@db:5432/hack
      - LOGGING=1
      - BACKEND_PORT=3000
      - COOKIE_TIMEOUT_MIN=60
      - MAX_SCAN_DEPTH=2
      - DELTA_SERVICE_URL=http://delta:3001
    restart: unless-stopped
    networks:
      - hackathon
    # volumes:                        # enable this to persist logs across restarts ( also uncomment the volume below)
    #   - backend_logs:/app/logs

volumes:
  postgresdb:
#  minio_data:
#  backend_logs:

networks:
  hackathon:
    driver: bridge
